"""
Minimal, secure webhook listener for mocked payment status updates.

Endpoints:
    POST /webhook/payments           - receive & store a signed webhook event
    GET  /payments/{payment_id}/events - fetch event history for a payment
    GET  /health                     - liveness check

Run locally:
    uvicorn app.main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI) once running:
    http://localhost:8000/docs
"""

import json
import logging

from fastapi import FastAPI, Header, HTTPException, Request, Depends
from fastapi.responses import JSONResponse
from sqlalchemy import asc
from sqlalchemy.orm import Session

from database import Base, engine, get_db
from models import PaymentEvent
from payload_parser import UnrecognizedPayloadFormat, parse_webhook_payload
from schemas import PaymentEventOut, WebhookAcceptedResponse
from security import SIGNATURE_HEADER, is_valid_signature

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("webhook")

# Create tables on startup if they don't exist yet.
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Payment Webhook Listener",
    description="Minimal, secure webhook listener for mocked payment status updates.",
    version="1.0.0",
)

@app.get("/health", tags=["meta"])
def health():
    return {"status": "healthy"}


@app.post(
    "/webhook/payments",
    response_model=WebhookAcceptedResponse,
    status_code=200,
    tags=["webhook"],
)
async def receive_payment_webhook(
    request: Request,
    x_razorpay_signature: str = Header(default=None, alias=SIGNATURE_HEADER),
    db: Session = Depends(get_db),
):
    # 1. Read the RAW body — signature must be verified against these exact
    #    bytes, not a re-serialized version of the parsed JSON.
    raw_body = await request.body()

    # 2. Verify authenticity BEFORE doing anything else with the payload.
    if not is_valid_signature(raw_body, x_razorpay_signature):
        log.warning("Rejected webhook: missing/invalid %s header", SIGNATURE_HEADER)
        raise HTTPException(status_code=403, detail="Invalid or missing signature")

    # 3. Parse JSON. Malformed JSON -> 400, per spec.
    try:
        payload = json.loads(raw_body)
    except json.JSONDecodeError:
        log.warning("Rejected webhook: invalid JSON body")
        raise HTTPException(status_code=400, detail="Invalid JSON body")

    # 4. Extract event_type, event_id, payment_id (Razorpay or PayPal shape).
    try:
        parsed = parse_webhook_payload(payload)
    except UnrecognizedPayloadFormat as exc:
        log.warning("Rejected webhook: %s", exc)
        raise HTTPException(status_code=400, detail=str(exc))

    # 5. Idempotency: if we've already stored this event_id, don't
    #    process it again — just acknowledge it so the provider doesn't
    #    keep retrying.
    existing = db.query(PaymentEvent).filter(
        PaymentEvent.event_id == parsed.event_id
    ).first()
    if existing:
        log.info("Duplicate event_id=%s ignored (already processed)", parsed.event_id)
        return WebhookAcceptedResponse(
            status="ok",
            message="Event already processed (duplicate ignored)",
            event_id=parsed.event_id,
            payment_id=parsed.payment_id,
        )

    # 6. Store the full payload.
    db_event = PaymentEvent(
        event_id=parsed.event_id,
        event_type=parsed.event_type,
        payment_id=parsed.payment_id,
        status=parsed.status,
        provider=parsed.provider,
        raw_payload=raw_body.decode("utf-8"),
    )
    db.add(db_event)
    db.commit()

    log.info(
        "Stored event_id=%s type=%s payment_id=%s provider=%s",
        parsed.event_id, parsed.event_type, parsed.payment_id, parsed.provider,
    )

    return WebhookAcceptedResponse(
        status="ok",
        message="Event received and stored",
        event_id=parsed.event_id,
        payment_id=parsed.payment_id,
    )


@app.get(
    "/payments/{payment_id}/events",
    response_model=list[PaymentEventOut],
    tags=["query"],
)
def get_payment_events(payment_id: str, db: Session = Depends(get_db)):
    events = (
        db.query(PaymentEvent)
        .filter(PaymentEvent.payment_id == payment_id)
        .order_by(asc(PaymentEvent.received_at))
        .all()
    )
    # Note: we deliberately return an empty list (not 404) for a
    # payment_id with no events — it's a valid query, just with zero
    # results, which is friendlier for API consumers polling for updates.
    return events


# --------------------------------------------------------------------------
# Custom error handler so HTTPExceptions come back in a consistent shape
# --------------------------------------------------------------------------
@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(
        status_code=exc.status_code,
        content={"status": "error", "message": exc.detail},
    )
